CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(120) NOT NULL,
    role            VARCHAR(32)  NOT NULL,
    phone           VARCHAR(40),
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN ('BOATER', 'STAFF', 'HARBORMASTER', 'ADMIN'))
);

CREATE TABLE vessel (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id             BIGINT       NOT NULL,
    name                 VARCHAR(120) NOT NULL,
    registration_number  VARCHAR(64)  NOT NULL,
    length_feet          DECIMAL(6,2) NOT NULL,
    beam_feet            DECIMAL(6,2) NOT NULL,
    draft_feet           DECIMAL(6,2) NOT NULL,
    vessel_type          VARCHAR(32)  NOT NULL,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_vessel_owner FOREIGN KEY (owner_id) REFERENCES app_user (id),
    CONSTRAINT uq_vessel_registration UNIQUE (registration_number),
    CONSTRAINT ck_vessel_type CHECK (vessel_type IN ('SAIL', 'POWER', 'CATAMARAN', 'OTHER')),
    CONSTRAINT ck_vessel_dims CHECK (length_feet > 0 AND beam_feet > 0 AND draft_feet > 0)
);

CREATE TABLE berth (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(16)  NOT NULL,
    pier             VARCHAR(32)  NOT NULL,
    max_length_feet  DECIMAL(6,2) NOT NULL,
    max_draft_feet   DECIMAL(6,2) NOT NULL,
    berth_type       VARCHAR(32)  NOT NULL,
    daily_rate       DECIMAL(10,2) NOT NULL,
    status           VARCHAR(32)  NOT NULL,
    notes            VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_berth_code UNIQUE (code),
    CONSTRAINT ck_berth_type CHECK (berth_type IN ('TRANSIENT', 'SEASONAL', 'LIVEABOARD')),
    CONSTRAINT ck_berth_status CHECK (status IN ('AVAILABLE', 'MAINTENANCE', 'OUT_OF_SERVICE')),
    CONSTRAINT ck_berth_rate CHECK (daily_rate >= 0),
    CONSTRAINT ck_berth_dims CHECK (max_length_feet > 0 AND max_draft_feet > 0)
);

CREATE TABLE reservation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id       BIGINT        NOT NULL,
    berth_id        BIGINT        NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    status          VARCHAR(32)   NOT NULL,
    nightly_rate    DECIMAL(10,2) NOT NULL,
    total_amount    DECIMAL(12,2) NOT NULL,
    late_cancel_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes           VARCHAR(1000),
    version         BIGINT        NOT NULL DEFAULT 0,
    created_by_id   BIGINT        NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    checked_in_at   TIMESTAMP WITH TIME ZONE,
    checked_out_at  TIMESTAMP WITH TIME ZONE,
    cancelled_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_res_vessel FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_res_berth FOREIGN KEY (berth_id) REFERENCES berth (id),
    CONSTRAINT fk_res_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id),
    CONSTRAINT ck_res_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT ck_res_dates CHECK (end_date > start_date),
    CONSTRAINT ck_res_amounts CHECK (nightly_rate >= 0 AND total_amount >= 0 AND late_cancel_fee >= 0)
);

CREATE INDEX idx_res_berth_dates ON reservation (berth_id, start_date, end_date);
CREATE INDEX idx_res_vessel ON reservation (vessel_id);
CREATE INDEX idx_res_status ON reservation (status);

CREATE TABLE waitlist_entry (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id        BIGINT       NOT NULL,
    preferred_start  DATE         NOT NULL,
    preferred_end    DATE         NOT NULL,
    min_length_feet  DECIMAL(6,2),
    status           VARCHAR(32)  NOT NULL,
    notes            VARCHAR(500),
    offered_berth_id BIGINT,
    offered_until    TIMESTAMP WITH TIME ZONE,
    created_by_id    BIGINT       NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_wl_vessel FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_wl_berth FOREIGN KEY (offered_berth_id) REFERENCES berth (id),
    CONSTRAINT fk_wl_created_by FOREIGN KEY (created_by_id) REFERENCES app_user (id),
    CONSTRAINT ck_wl_status CHECK (status IN ('WAITING', 'OFFERED', 'ACCEPTED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_wl_dates CHECK (preferred_end > preferred_start)
);

CREATE INDEX idx_wl_status_created ON waitlist_entry (status, created_at);

CREATE TABLE work_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id       BIGINT,
    berth_id        BIGINT,
    title           VARCHAR(160) NOT NULL,
    description     VARCHAR(2000) NOT NULL,
    priority        VARCHAR(16)  NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    category        VARCHAR(32)  NOT NULL,
    reported_by_id  BIGINT       NOT NULL,
    assigned_to_id  BIGINT,
    labor_hours     DECIMAL(6,2),
    parts_cost      DECIMAL(10,2) NOT NULL DEFAULT 0,
    labor_rate      DECIMAL(10,2) NOT NULL DEFAULT 85.00,
    due_at          TIMESTAMP WITH TIME ZONE,
    started_at      TIMESTAMP WITH TIME ZONE,
    completed_at    TIMESTAMP WITH TIME ZONE,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_wo_vessel FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_wo_berth FOREIGN KEY (berth_id) REFERENCES berth (id),
    CONSTRAINT fk_wo_reported_by FOREIGN KEY (reported_by_id) REFERENCES app_user (id),
    CONSTRAINT fk_wo_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES app_user (id),
    CONSTRAINT ck_wo_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT ck_wo_status CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_wo_category CHECK (category IN ('ELECTRICAL', 'PLUMBING', 'HULL', 'ENGINE', 'DOCK', 'OTHER'))
);

CREATE INDEX idx_wo_status_priority ON work_order (status, priority);
CREATE INDEX idx_wo_assigned ON work_order (assigned_to_id);

CREATE TABLE invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number  VARCHAR(32)   NOT NULL,
    customer_id     BIGINT        NOT NULL,
    reservation_id  BIGINT,
    work_order_id   BIGINT,
    status          VARCHAR(32)   NOT NULL,
    subtotal        DECIMAL(12,2) NOT NULL,
    tax_amount      DECIMAL(12,2) NOT NULL,
    total_amount    DECIMAL(12,2) NOT NULL,
    issued_at       TIMESTAMP WITH TIME ZONE,
    paid_at         TIMESTAMP WITH TIME ZONE,
    voided_at       TIMESTAMP WITH TIME ZONE,
    notes           VARCHAR(1000),
    version         BIGINT        NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_invoice_number UNIQUE (invoice_number),
    CONSTRAINT fk_inv_customer FOREIGN KEY (customer_id) REFERENCES app_user (id),
    CONSTRAINT fk_inv_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id),
    CONSTRAINT fk_inv_work_order FOREIGN KEY (work_order_id) REFERENCES work_order (id),
    CONSTRAINT ck_inv_status CHECK (status IN ('DRAFT', 'ISSUED', 'PAID', 'VOID')),
    CONSTRAINT ck_inv_amounts CHECK (subtotal >= 0 AND tax_amount >= 0 AND total_amount >= 0)
);

CREATE TABLE invoice_line_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT        NOT NULL,
    description VARCHAR(255)  NOT NULL,
    quantity    DECIMAL(10,2) NOT NULL,
    unit_price  DECIMAL(10,2) NOT NULL,
    line_total  DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_ili_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE,
    CONSTRAINT ck_ili_qty CHECK (quantity > 0),
    CONSTRAINT ck_ili_price CHECK (unit_price >= 0)
);

CREATE TABLE audit_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id      BIGINT,
    action        VARCHAR(64)  NOT NULL,
    entity_type   VARCHAR(64)  NOT NULL,
    entity_id     BIGINT,
    details       VARCHAR(2000),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_entity ON audit_event (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_event (created_at);

-- Single-row counter for collision-free invoice numbers across restarts and instances.
CREATE TABLE invoice_sequence (
    id          INT PRIMARY KEY,
    next_value  BIGINT NOT NULL
);

INSERT INTO invoice_sequence (id, next_value) VALUES (1, 1000);

CREATE INDEX idx_invoice_reservation ON invoice (reservation_id);
CREATE INDEX idx_invoice_work_order ON invoice (work_order_id);
CREATE INDEX idx_wl_offered_berth ON waitlist_entry (offered_berth_id, status);
